### ISSUE TITLE
A Multiline hook breaks manifest structure

### ISSUE THREAD

**Issue by en30** [pepabo/capistrano-stretcher#10]
YAML accepts multiline string, but if I write 
```yaml
www:
  pre:
    - |
      if [ -d $FOO ]; then
        # do somoething
      fi
```
to `config/stretcher.yml.erb`.

https://github.com/pepabo/capistrano-stretcher/blob/50eb79717d7bca7b1ff71486076cfb8fadb4c2ee/lib/capistrano/templates/manifest.yml.erb#L4-L8

will be 

```yaml
commands:
  pre:
    - if [ -d $FOO ]; then
  # do somoething
fi
```

This is not valid YAML.
